# Results

```{r, echo=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(tidyr)
library(patchwork)
library(reactable)
library(viridis)
```

```{r, echo=FALSE, include=FALSE}
# load the cleaned dataset
df <- readRDS(file='data/cleaned_DOHMH_New_York_City_Restaurant_Inspection_Results.Rda')

# shorten the column names so they don't overlap in the plot
# names(df) <- abbreviate(names(df), minlength=5)

# df <- na.omit(df)
df$grade <- fct_relevel(df$grade, "A", "B", "C", "G", "N", "P", "Z")
df$score <- as.numeric(df$score)
df <- df[row.names(unique(df[c('camis','insp.date','score','grade')])),]
df$score <- ifelse(df$action == 'No violations were recorded at the time of this inspection.', 0, df$score)
df <- df %>% drop_na(score)

df <- subset(df,!(boro %in% c('0','210')))
df <- subset(df,!(flag %in% c('Not Applicable')))



###########################################



#Filter on inspection type, score, grade
Inspections <- df %>%
  select(camis,insp.date)

#Select distinct inspections
Inspections_Distinct <- distinct(Inspections)

#Select most recent inspection date
MostRecentInsp <- Inspections_Distinct %>%
  group_by(camis) %>%
  slice(which.max(as.Date(insp.date,'%m/%d/%Y')))

#Join most recent inspection with original dataset
inner_join(df,MostRecentInsp, by = "camis","insp.date")

#Select restaurant inspection data based on most recent inspection date
Final <- df %>% inner_join(MostRecentInsp)

#Select distinct restaurant inspection data
df_recent <- distinct(Final)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_plot1 <- df[df$camis %in% c(40710411,50075252,40391498,50036714,50042132,50051826,41485818,41303034),]

# ver2
# df_plot1 <- df[df$camis %in% names(which(table(df$camis) > 3)),]
# df_plot1 <- df_plot1[df_plot1$camis %in% sample(unique(df_plot1$camis),10),]

ggplot(df_plot1, aes(x=insp.date, y=score, group = camis, color = boro)) +
  geom_line() + 
  geom_point(size = 2.5) +
  xlab("Inspection Date") +
  ylab("Violation Score") +
  labs(color = "Borough") +
  ggtitle("Inspection Score changes over Date") +
  theme(plot.title = element_text(face = "bold")) +
  theme(legend.position = c(0.8, 0.65), legend.key.size = unit(0.5, 'cm'))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

df_plot2 <- df_recent
df_plot2$violation <- ifelse(df_plot2$action == 'No violations were recorded at the time of this inspection.', 'No Violation', 'Violation')

df_plot2 <- df_plot2 %>% 
  group_by(boro,flag) %>% 
  summarise(count = n()) %>% 
  na.omit %>% 
  mutate(freq = count / sum(count))

ggplot(df_plot2, aes(x = flag, y = freq, fill = flag)) +
  geom_bar(position = "dodge", stat = "identity") +
  facet_wrap(~boro) + 
  scale_y_continuous(limits=c(0,0.8)) +
  ggtitle("Which Area has more # of Critical Violations?") +
  scale_fill_manual(values = c("#b2df8a", "#a6cee3")) +
  labs(y = "Frequency", fill = "") + 
  theme(plot.title = element_text(face = "bold"), axis.title.x=element_blank(), legend.position = c(0.85, 0.28))

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

df_plot3 <- df_recent

chain <- df %>%
  select(camis,dba)
chain <- distinct(chain)
chain <- chain %>% 
  group_by(dba) %>% 
  summarise(count = n()) %>% 
  subset(count > 3)

df_plot3$chain <- ifelse(df_plot3$dba %in% chain$dba, 'Chain', 'Non-Chain')

# df_plot3 <- df_plot3 %>% 
#   group_by(boro, chain) %>% 
#   summarise(Mean_Score = mean(score))
df_plot3 <- subset(df_plot3, !(boro %in% c('0','210')))


ggplot(df_plot3, aes(x=chain, y=score, fill = chain)) +
  geom_boxplot() +
  facet_wrap(~boro) +
  scale_y_continuous(limits = quantile(df_plot3$score, c(0.1, 0.82))) + 
  ggtitle("Which one violates more?",
          subtitle = "Chain Restaurant vs Non-chain Restaurant") +
  labs(x = "Type", y = "Violation Score") +
  theme_grey(16) +
  theme(plot.title = element_text(face = "bold")) +
  theme(plot.subtitle = element_text(face = "bold", color = "grey35")) +
  theme(legend.position = c(0.85, 0.28))


```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

df_plot4 <- df_recent
df_plot4 <- df_plot4 %>% 
  group_by(cuisine) %>% 
  summarise(Mean = mean(score), n = n())

df_plot4 <- na.omit(df_plot4)
df_plot4 <- subset(df_plot4, n>100)
#################################################################

# create a theme for dot plots, which can be reused
theme_dotplot <- theme_bw(14) +
  theme(axis.text.y = element_text(size = rel(.75)),
        axis.ticks.y = element_blank(),
        axis.title.x = element_text(size = rel(.75)),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size = 0.5),
        panel.grid.minor.x = element_blank())


# create the plot
ggplot(df_plot4, aes(x = Mean, y = reorder(cuisine, Mean))) +
  geom_point(color = "red") +
  theme_dotplot +
  xlab("Average Violation Score") +
  ylab("Cuisine Category \n(Include only n>100)") +
  ggtitle("Which category of Cuisine \nreceived higher violation score?")

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

df_plot5 <- df

df_plot5 <- subset(df_plot5,!(vio.code %in% c('02G','02B','20D','04N','02H','02I','20D','02C','02J')))

df_plot5 <- df_plot5 %>% drop_na(vio.code)

vio_count <- df_plot5 %>% 
  group_by(vio.code) %>% 
  summarize(count = n())
# major_vio <- vio_count[vio_count$count>1500,]
# df_plot5 <- df_plot5[df_plot5$vio.code %in% major_vio$vio.code,]
df_plot5 <- df_plot5 %>% 
  group_by(insp.date,vio.code,vio.desc) %>% 
  summarize(count = n())

temp <- df_plot5 %>% 
  group_by(vio.code) %>% 
  summarize(count = n())
temp <- temp[temp$count>1000,]$vio.code
df_plot5 <- df_plot5[df_plot5$vio.code %in% temp,]

prop <- df_plot5 %>% 
  group_by(insp.date) %>% 
  summarize(countsum = sum(count))
prop <- prop[prop$countsum >10,]

df_plot5 <- merge(df_plot5, prop, by = 'insp.date')
df_plot5$prop <- df_plot5$count/df_plot5$countsum
df_plot5 <- df_plot5[!duplicated(df_plot5[c('insp.date','vio.code')]),]
df_plot5 <- df_plot5[df_plot5$insp.date >= '2018-01-01',]


ggplot(df_plot5, aes(x=insp.date, y=prop, color =vio.code)) +
  geom_point() + 
  facet_wrap(~vio.code, scales = 'free') +
  geom_line(stat = "smooth", method = lm, color = "red", size = 1, alpha = 0.3) +
  labs(y = "Frequency", x = "Inspection Date", color = "Violation Code") + 
  ggtitle("Which Violation increases after COVID-19?") +
  theme(plot.title = element_text(face = "bold"))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

codetable <- unique(df_plot5[c('vio.code','vio.desc')])
colnames(codetable) <- c('Violation_Code', 'Description')
reactable(codetable)

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_plot6 <- df_recent
df_plot6 <- subset(df_plot6,!(vio.code %in% c('02G','02B','20D','04N','02H','02I','20D','02C','02J')))
df_plot6 <- df_plot6 %>% drop_na(vio.code)

recent_vio <- df_plot6 %>% 
  group_by(vio.code,vio.desc) %>% 
  summarize(count = n())
top10vio_recent <- recent_vio[recent_vio$count>1000,]
top10vio_recent <- top10vio_recent[order(-top10vio_recent$count),]
colnames(top10vio_recent) <- c('Violation_Code', 'Description', 'Count')
top10vio_recent$pct <- top10vio_recent$Count / sum(top10vio_recent$Count) * 100
top10vio_recent$pct <- round(top10vio_recent$pct, digits = 0)

ggplot(top10vio_recent, aes(x='', y=pct, fill=reorder(Violation_Code,Count)))+
  geom_bar(stat='identity')+
  theme_void()+
  coord_polar('y', start=0)+
  geom_text(aes(label=paste0(round(pct,1), '%')),
            position=position_stack(vjust=0.5),
            color='white', family='serif', size=7)+
  scale_fill_viridis(option="H",discrete=TRUE) +
  labs(fill="Violation Code") + 
  ggtitle("Most recently, which violations are major?") +
  theme(plot.title = element_text(face = "bold", size = 15))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

top10vio_recent <- top10vio_recent[order(top10vio_recent$Count),]
reactable(top10vio_recent[c('Violation_Code','Description')])

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_plot7 <- df %>% drop_na(grade)
df_plot7 <- subset(df_plot7,!(grade %in% c('G')))

df_plot7 <- df_plot7 %>% 
  group_by(boro,grade) %>% 
  summarise(count = n()) %>% 
  na.omit
temp <- df_plot7 %>% 
  group_by(grade) %>% 
  summarise(total = sum(count))
df_plot7 <- merge(df_plot7, temp, by = "grade")
df_plot7$freq <- round(df_plot7$count/df_plot7$total, digits = 2)


ggplot(df_plot7, aes(x = grade, y = freq, fill = boro)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(x="Grade",y="Frequency",fill="Borough") + 
  ggtitle("Which Borough gets Better Grade?") +
  theme(plot.title = element_text(face = "bold", size = 15)) +
  scale_fill_viridis(option="G",discrete=TRUE) +
  geom_text(aes(label = ifelse(freq == 0, "", scales::percent(freq))),
            position = position_fill(vjust = 0.5),col = 'white')


```
